version: 0.2
phases:
  install:
    commands:
      # 1. 환경 설정 및 설치
      - echo Installing dependencies...
      # CodeBuild 환경에 Maven 빌드를 위한 Java 설치 (예시: Java 17)
      - apt-get update -y
      - apt-get install -y openjdk-17-jdk

  pre_build:
    commands:
      - echo Pre-build phase completed

  build:
    commands:
      - echo Build started on `date`
      # 2. Maven 빌드 실행 (테스트를 제외하고 패키징)
      - mvn clean package -DskipTests
      - echo Build completed on `date`

artifacts:
  files:
    # 3. 배포 아티팩트 구성
    # 빌드된 JAR 파일 (프로젝트명과 버전은 pom.xml에 정의된 것을 따릅니다)
    # Maven은 JAR 파일을 보통 target 디렉토리 아래에 생성합니다.
    - target/*.jar
    - appspec.yml # CodeDeploy 지침서
    - scripts/** # 서버 제어 스크립트 폴더 전체
  discard-paths: yes # 아티팩트를 만들 때 불필요한 상위 폴더 경로를 제거합니다.
